console.log("Sedan IIFE", Sedan)
console.log("Sedan color: ", Sedan.getColor())
console.log("Sedan type: ", Sedan.getType())
console.log("Sedan set occupancy: ", Sedan.setOccupancy(6))
console.log("Sedan get occupancy: ", Sedan.getOccupancy())